/**
  Generated by Exodia
**/

import Foundation
import ObjectMapper

final class {{ model.name }}: Mappable {
  {% for property in model.properties %}
  {% if property.defaultValue %}var {{ property.name }}: {{ property.type }} = {{ property.defaultValue }}{% else %}var {{ property.name }}: {{ property.type }}?{% endif %}{% endfor %}

  required init?(map: Map) {
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"]{% endfor %}
  }

  func mapping(map: Map) {
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"] {% endfor %}
  }
}
