/**
Generated by Exodia
**/

import Foundation
import RealmSwift
import ObjectMapper
import ObjectMapper_Realm

final class {{ model.name }}: Object, Mappable {
  {% for property in model.properties %}
  {% if property.defaultValue %}dynamic var {{ property.name }}: {{ property.type }} = {{ property.defaultValue }}{% else %}dynamic var {{ property.name }}: {{ property.type }}?{% endif %}{% endfor %}

  required convenience init?(map: Map) {

    self.init()
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"]{% endfor %}
  }

  func mapping(map: Map) {
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"]{% endfor %}
  }
}
