/**
  Generated by Exodia
**/

import Foundation
import ObjectMapper

struct {{ model.name }}: Mappable {
  {% for property in model.properties %}
  {% if property.defaultValue %}var {{ property.name }}: {{ property.type }} = {{ property.defaultValue }}{% else %}var {{ property.name }}: {{ property.type }}?{% endif %}{% endfor %}
  
  init?(map: Map) {
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"]{% endfor %}
  }
  
  mutating func mapping(map: Map) {
    {% for property in model.properties %}
    {{ property.name }} <- map["{{ property.key }}"] {% endfor %}
  }
}
