# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Exodia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Exodia
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'
  pod 'RxOptional'
  pod 'ObjectMapper'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'Stencil'

end
